/* Generated by AN DISI Unibo */ 
package it.unibo.ledqakactor

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Ledqakactor ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "setup"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		var ledState = led.state.LedState(led.state.CurrStateLed.OFF) 
		return { //this:ActionBasciFsm
				state("setup") { //this:State
					action { //it:State
						println("$name | setup")
					}
					 transition( edgeName="goto",targetState="off", cond=doswitch() )
				}	 
				state("on") { //this:State
					action { //it:State
						
									ledState.updateLedState(led.state.CurrStateLed.ON)	
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep(ledState.toJsonString() 
						)
					}
					 transition(edgeName="t00",targetState="blink",cond=whenDispatch("blink"))
					transition(edgeName="t01",targetState="off",cond=whenDispatch("turnOff"))
				}	 
				state("off") { //this:State
					action { //it:State
						
									ledState.updateLedState(led.state.CurrStateLed.OFF)	
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep(ledState.toJsonString() 
						)
					}
					 transition(edgeName="t02",targetState="on",cond=whenDispatch("turnOn"))
					transition(edgeName="t03",targetState="blink",cond=whenDispatch("blink"))
				}	 
				state("blink") { //this:State
					action { //it:State
						
									ledState.updateLedState(led.state.CurrStateLed.BLINKING)	
						println("$name in ${currentState.stateName} | $currentMsg")
						updateResourceRep(ledState.toJsonString() 
						)
					}
					 transition(edgeName="t04",targetState="on",cond=whenDispatch("turnOn"))
					transition(edgeName="t05",targetState="off",cond=whenDispatch("turnOff"))
				}	 
			}
		}
}
