version: '3.3'
services: 
    wasteservice:
        image: wasteservice-1.0
        ports:
            - 8055:8055/tcp
            - 8055:8055/udp
    robot:
        image: basicrobot22-2.0
        ports:
            - 8020:8020/tcp
            - 8020:8020/udp 
        depends_on:
            - wasteservice
    wenv:
        image: wenv-1.0
        ports:
            8090:8090/tcp
            8091:8091/tcp
            8090:8090/udp
            8091:8091/udp
        depends_on:
            - robot
            - wasteservice

