/* Generated by AN DISI Unibo */ 
package it.unibo.led

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Led ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		val interruptedStateTransitions = mutableListOf<Transition>()
		 
				var led : `it.unibo`.radarSystem22.domain.interfaces.ILed? = null
				var flagBlink = false
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						 unibo.comm22.utils.ColorsOut.outappl("$name	|	starting...", unibo.comm22.utils.ColorsOut.YELLOW) 
						
									led = utility.LedFactory.createLed()
									led!!.turnOff()
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						 unibo.comm22.utils.ColorsOut.outappl("$name	|	waiting...", unibo.comm22.utils.ColorsOut.YELLOW) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition(edgeName="t058",targetState="blinkon",cond=whenDispatch("blink"))
					transition(edgeName="t059",targetState="on",cond=whenDispatch("turnon"))
					transition(edgeName="t060",targetState="off",cond=whenDispatch("turnoff"))
				}	 
				state("on") { //this:State
					action { //it:State
						 unibo.comm22.utils.ColorsOut.outappl("$name	|	TurnOn Led", unibo.comm22.utils.ColorsOut.YELLOW) 
						led!!.turnOn() 
						 flagBlink = false  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("off") { //this:State
					action { //it:State
						 unibo.comm22.utils.ColorsOut.outappl("$name	|	TurnOff Led", unibo.comm22.utils.ColorsOut.YELLOW) 
						led!!.turnOff() 
						 flagBlink = false  
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("blinkon") { //this:State
					action { //it:State
						if(  flagBlink == false 
						 ){ unibo.comm22.utils.ColorsOut.outappl("$name	|	Blink Led", unibo.comm22.utils.ColorsOut.YELLOW) 
						 flagBlink = true  
						}
						led!!.turnOn() 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		//sysaction { //it:State
				 	 		  stateTimer = TimerActor("timer_blinkon", 
				 	 			scope, context!!, "local_tout_led_blinkon", 300.toLong() )
				 	 		//}
					}	 	 
					 transition(edgeName="t061",targetState="blinkoff",cond=whenTimeout("local_tout_led_blinkon"))   
					transition(edgeName="t062",targetState="on",cond=whenDispatch("turnon"))
					transition(edgeName="t063",targetState="off",cond=whenDispatch("turnoff"))
				}	 
				state("blinkoff") { //this:State
					action { //it:State
						led!!.turnOff() 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
				 	 		//sysaction { //it:State
				 	 		  stateTimer = TimerActor("timer_blinkoff", 
				 	 			scope, context!!, "local_tout_led_blinkoff", 300.toLong() )
				 	 		//}
					}	 	 
					 transition(edgeName="t064",targetState="blinkon",cond=whenTimeout("local_tout_led_blinkoff"))   
					transition(edgeName="t065",targetState="on",cond=whenDispatch("turnon"))
					transition(edgeName="t066",targetState="off",cond=whenDispatch("turnoff"))
				}	 
			}
		}
}
